---
apiVersion: v1
kind: Service
metadata:
  name: orch-frontend-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      protocol: "TCP"
  selector:
    app: orch-frontend-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orch-frontend-deployment
spec:
  selector:
    matchLabels:
      app: orch-frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: orch-frontend-app
    spec:
      containers:
        - name: orch-frontend-container
          image: wi18/kubernetes-orch-frontend
          ports:
            - containerPort: 80

