---
apiVersion: v1
kind: Service
metadata:
  name: simple-deployment-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      protocol: "TCP"
  selector:
    app: simple-deployment-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  selector:
    matchLabels:
      app: simple-deployment-app
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-deployment-app
    spec:
      containers:
        - name: simple-deployment-container
          image: wi18/docker-web-page
          ports:
            - containerPort: 80

